#spring:
#  application:
#    name : activityservice
#
#data:
#  mongodb:
#    uri: mongodb://localhost:27017/aiactivityfitnesss
#    database: aiactivityfitness
#
#server:
#  port: 8082
spring:
  application:
    name: activityservice

  data:
    mongodb:
      uri: mongodb://localhost:27017/aiactivityfitness
      database: aiactivityfitness
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761//eureka/
server:
  port: 8082

